<?php
// This file is part of Moodle - http://moodle.org/
//
// Moodle is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Moodle is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Moodle.  If not, see <http://www.gnu.org/licenses/>.

/**
 * Plugin strings are defined here.
 *
 * @package     qtype_programmingtask
 * @category    string
 * @copyright   2019 ZLB-ELC Hochschule Hannover <elc@hs-hannover.de>
 * @license     http://www.gnu.org/copyleft/gpl.html GNU GPL v3 or later
 */
defined('MOODLE_INTERNAL') || die();

$string['addanswertext'] = 'Add answer field';
$string['addfreetextfieldsettings'] = 'Add settings for another free text input field';
$string['chose_communicator'] = 'Communicator';
$string['client_polling_interval'] = 'Client polling interval';
$string['combinedresult'] = 'Combined result';
$string['commonsettings'] = 'Common settings';
$string['currentlybeinggraded'] = 'This task is currently being graded by the grader';
$string['defaultlang'] = 'Default programming language';
$string['descriptionfreetextinputnames'] = 'In the following you can specify settings for each free text input field';
$string['detailedfeedback'] = 'Detailed feedback';
$string['showstudscorecalcscheme'] = 'Show students score calculation scheme';
$string['enablecustomsettingsforfreetextinputfield'] = 'Enable custom settings for free text input field #';
$string['enablecustomsettingsforfreetextinputfields'] = 'Enable custom settings for free text input fields';
$string['enablefilesubmissions'] = 'Enable file submissions';
$string['enablefreetextsubmissions'] = 'Enable free text submissions';
$string['external_settings-graders'] = 'Programming task graders';
$string['feedback'] = 'Feedback';
$string['filename'] = 'Filename';
$string['files'] = 'Files';
$string['freetextinputautogeneratedname'] = 'Use auto-generated file names';
$string['freetextinputnamesettingstandard'] = 'Standard file name setting for all input fields';
$string['freetextinputteachername'] = 'Use pre-set name as file name';
$string['freetextinputstudentname'] = 'Let students set a file name';
$string['freetextsubmissions'] = 'Freetext submissions';
$string['ftsmaxnumfields'] = 'Maximal number of free text input fields';
$string['ftsnuminitialfields'] = 'Initial number of free text input fields';
$string['ftsoverwrittenlang'] = 'Programming language';
$string['ftspathinsubmissionfile'] = 'Path in the submission zip file for free text submissions';
$string['ftsstandardlang'] = 'Programming language for freetext submissions';
$string['grader'] = 'Grader';
$string['gradercurrentlynotavailable'] = 'The grader for this task is currently not available. You can still submit your solution but you won\'t get a result. You will only get a result once the grader is available again and either you or a teacher resubmits your submission.';
$string['gradersettings'] = 'Grader settings';
$string['gradeprocessfinished'] = 'At least one grade process finished. Do you want to reload the page to display the results?';
$string['grappa_url'] = 'Grappa-URL';
$string['hasbeennullified'] = 'has been nullified';
$string['initialnumberfreetextfieldsgreaterthanmax'] = 'Initial number of free text input fields must not be greater than maximal number of free text input fields';
$string['internaldescription'] = 'Internal description';
$string['invalidproformanamespace'] = 'Could not detect ProFormA-version. Can\'t validate task.xml file or extract data from it. Supported versions: {$a}';
$string['lmsid'] = 'LMS-ID';
$string['loadproformataskfile'] = 'Extract information';
$string['minimum'] = 'Minimum';
$string['maximum'] = 'Maximum';
$string['needsgradingbyteacher'] = 'An error occurred during the grading process, your submission needs manual grading by a teacher.';
$string['nofeedback'] = 'No feedback given';
$string['nofilessubmitted'] = 'You didn\'t submit any files as a solution to the task.';
$string['noresponseyet'] = 'No responset yet';
$string['nosubmissionpossible'] = 'Your teacher didn\'t enable any way of submitting your solution';
$string['nosummaryavailable'] = 'No summary available.';
$string['password'] = 'Password';
$string['pluginname'] = 'Programming task';
$string['pluginname_help'] = 'Programmingtask questions allow the use of ProFormA tasks.';
$string['pluginname_link'] = 'question/type/programmingtask';
$string['pluginnameadding'] = 'Adding a ProFormA programming task';
$string['pluginnameediting'] = 'Editing a ProFormA programming task';
$string['pluginnamesummary'] = 'Questions of this type represent a ProFormA task.';
$string['proformataskfilerequired'] = 'You need to supply a ProFormA task file';
$string['previousgradernotavailable'] = 'The previously selected grader is currently not available, it was manually added to the list of available graders. This might be an indicator for a problem with the grader.';
$string['privacy:metadata:grader_link'] = 'In order to obtain a grade the users submission is sent to a grading software, possibly using a middleware.';
$string['proformataskfileupload'] = 'ProFormA task file';
$string['proformataskfileupload_help'] = 'You can add a ProFormA task file (zip file) to this file picker. If you click the according button the necessary informations will be automatically extracted and inserted into the corresponding form elements on this page.';
$string['programminglanguage'] = 'Programming language';
$string['providedfiles'] = 'Provided files';
$string['redobuttontext'] = 'Retry programming task';
$string['reloadpage'] = 'Reload page?';
$string['reload'] = 'Reload';
$string['removelastanswertext'] = 'Remove last answer field';
$string['retrievegradingresults'] = 'Retrieve grading results';
$string['remove_leftover_responsefiles'] = 'Remove leftover response files';
$string['score'] = 'Score';
$string['scorecalculationscheme'] = 'Score calculation scheme';
$string['submission'] = 'Submission';
$string['submissionsettings'] = 'Submission settings';
$string['submittedfiles'] = 'Submitted files';
$string['subtests'] = 'Subtests';
$string['subtest'] = 'Subtest';
$string['summarizedfeedback'] = 'Summarized feedback';
$string['taskfile'] = 'ProFormA task file';
$string['taskuuid'] = 'Task-UUID';
$string['taskuuidhaswronglength'] = 'Wrong length - uuid has to have 36 characters (32 hex digits and 4 dashes)';
$string['taskuuidrequired'] = 'You need to supply a valid task uuid';
$string['teacherfeedback'] = 'Teacher feedback';
$string['test'] = 'Test';
$string['testdescription'] = 'Test description';
$string['testgroup'] = 'Testgroup';
$string['testresult'] = 'Test result';
$string['timeout'] = 'Grappa-Timeout';
$string['yourcode'] = 'Your code';
