<?php
// This file is part of Moodle - http://moodle.org/
//
// Moodle is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Moodle is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Moodle.  If not, see <http://www.gnu.org/licenses/>.

defined('MOODLE_INTERNAL') || die();

global $CFG;
require_once($CFG->dirroot . '/question/engine/tests/helpers.php');
require_once($CFG->dirroot . '/question/type/moopt/externallib.php');
require_once($CFG->dirroot . '/question/type/moopt/locallib.php');

/**
 * Helper class for automatic generation of moopt questions.
 */
class qtype_moopt_test_helper extends question_test_helper
{
    public function get_test_questions(): array
    {
        return ['graflap_grammar_for_nfa1', 'dummygrader_quicktest', 'graja_pointrotate', 'asqlg_quicktest', 'creation_task'];
    }

    public function get_moopt_question_form_data_asqlg_quicktest(): stdClass
    {
        // The asqlg grader used must provide the uri: de.hsh.inform.hochschule.postgres
        return $this->extract_form_data_from_task("fixtures/tasks/asqlg_quicktest.zip", 'asqlg');
    }

    public function get_moopt_question_form_data_dummygrader_quicktest(): stdClass
    {
        return $this->extract_form_data_from_task("fixtures/tasks/dummygrader_quicktest.xml", 'dummygrader');
    }

    public function get_moopt_question_form_data_graflap_grammar_for_nfa1(): stdClass
    {
        return $this->extract_form_data_from_task("fixtures/tasks/graflap_grammar_for_nfa1.zip", 'graflap');
    }

    public function get_moopt_question_form_data_graja_pointrotate(): stdClass
    {
        // Version of the Grader must be 2.6 to grade this task
        return $this->extract_form_data_from_task("fixtures/tasks/graja_pointrotate.zip", 'graja');
    }

    public function get_moopt_question_form_data_creation_task(): stdClass
    {
        return $this->extract_form_data_from_task("fixtures/tasks/question_creation_task.xml", 'dummygrader');
    }

    /**
     * Extracts the form data to create a moopt question from a specific task file by calling the moopt webservice directly
     *
     * The custom behat step moopt_is_configured_for_testing() must be called before any question can be generated by this method
     * @param string $taskfilepath The path to the taskfile from which the question should be generated
     * @param string $expectedgrader A name for the specific grader that is used for that question. $CFG must contain the specific grader id
     *                               for the gradername given here by adding the following into config.php of the moodle installation:
     *                               - <code>$CFG->behat_qtype_moopt_grader_name_<$expectedgrader> = '<Name of the real grader used>';</code>
     *                               - <code>$CFG->behat_qtype_moopt_grader_version_<$expectedgrader> '<Version of the real grader used>';</code>
     * @return stdClass The formdata for the generated question.
     */
    private function extract_form_data_from_task(string $taskfilepath, string $expectedgrader): stdClass {
        global $CFG, $USER;

        // Upload the task into an unused draft area because the moopt service needs the task to lie there to extract the info from it
        $draftitemid = file_get_unused_draft_itemid();
        $usercontext = context_user::instance($USER->id);
        $fullpath = $CFG->dirroot . '/question/type/moopt/tests/behat/' . $taskfilepath;
        $fs = get_file_storage();
        $fs->create_file_from_pathname([
            'contextid' => $usercontext->id,
            'component' => 'user',
            'filearea'  => 'draft',
            'itemid'    => $draftitemid,
            'filepath'  => '/',
            'filename'  => basename($fullpath),
        ], $fullpath);

        // call the webservice method directly to extract task info
        $info = qtype_moopt_external::extract_task_infos_from_draft_file($draftitemid);

        if (isset($info['error'])) {
            throw new moodle_exception('Failed to extract task info from ' . $taskfilepath . ': ' . $info['error']);
        }

        $formdata = new stdClass();

        $formdata->name = $info['title'];
        $formdata->questiontext = ['text' => $info['description'], 'format' => FORMAT_MOODLE];
        $formdata->generalfeedback = ['text' => $info['filesdisplayedingeneralfeedback'], 'format' => FORMAT_MOODLE];
        $formdata->defaultmark = $info['maxscoregradinghints'];
        $formdata->penalty = 0.3333333; //Default, would get a wrong value (0) when missing
        $formdata->internaldescription = ['text' => $info['internaldescription'], 'format' => FORMAT_HTML];
        $formdata->taskuuid = $info['taskuuid'];
        $formdata->proformataskfileupload = $draftitemid;
        $formdata->enablefilesubmissions = (int) $info['enablefileinput'];

        $formdata->showstudgradingscheme = 1;
        $formdata->showstudscorecalcscheme = 1;

        $freetextsettings = $info['freetextfilesettings'];
        $ftsmaxnumfields = count($freetextsettings);
        if ($ftsmaxnumfields > 0) {
            $formdata->enablefreetextsubmissions = 1;
            $formdata->ftsnuminitialfields = $ftsmaxnumfields;
            $formdata->ftsmaxnumfields = $ftsmaxnumfields;
            $formdata->ftsautogeneratefilenames = 0;
            // Default to the first option, then override if a proglang matches (mirrors the UI select default).
            $formdata->ftsstandardlang = array_key_first(PROFORMA_ACE_PROGLANGS);
            foreach (PROFORMA_ACE_PROGLANGS as $key => $displayname) {
                if (strtolower($displayname) === strtolower($info['proglang'])) {
                    $formdata->ftsstandardlang = $key;
                    break;
                }
            }
            $formdata->enablecustomsettingsforfreetextinputfields = 1;

            for ($i = 0; $i < $ftsmaxnumfields; $i++) {
                $setting = $freetextsettings[$i];
                $formdata->{"enablecustomsettingsforfreetextinputfield$i"} = (int) $setting['enablecustomsettings'];
                $formdata->{"namesettingsforfreetextinput$i"} = (int) !$setting['usefixedfilename'];
                $formdata->{"freetextinputfieldname$i"} = $setting['defaultfilename'];
                $formdata->{"freetextinputfieldtemplate$i"} = $setting['filecontent'];
                $formdata->{"ftsoverwrittenlang$i"} = $setting['proglang'];
                $formdata->{"ftsinitialdisplayrows$i"} = $setting['initialdisplayrows'];
            }
        } else {
            $formdata->enablefreetextsubmissions = 0;
        }

        // Get the provided graders from the middleware
        static $graders = null; //Cache
        if ($graders === null) {
            $serviceurl = get_config('qtype_moopt', 'service_url');
            try {
                $graders = \qtype_moopt\utility\communicator\communicator_factory::get_instance()->get_graders()['graders'];
            } catch (Exception $e) {
                throw new moodle_exception("Could not fetch the grader list from '$serviceurl': " . $e->getMessage());
            }
        }
        // Resolve the specific grader
        $gradername_setting = 'behat_qtype_moopt_grader_name_' . $expectedgrader;
        $graderversion_setting = 'behat_qtype_moopt_grader_version_' . $expectedgrader;
        if (!empty($CFG->{$gradername_setting}) && !empty($CFG->{$graderversion_setting})) {
            $grader_found = false;
            foreach ($graders as $grader) {
                if ($CFG->{$gradername_setting} === $grader['name'] && $CFG->{$graderversion_setting} === $grader['version']) {
                    $grader_found = true;
                    $formdata->graderselect = get_html_representation_of_graderid($grader['name'], $grader['version']);

                    // Defaults from edit_moopt_form.php
                    $formdata->resultspecformat = PROFORMA_RESULT_SPEC_FORMAT_ZIP;
                    $formdata->resultspecstructure = PROFORMA_SEPARATE_FEEDBACK_TYPE;
                    $formdata->studentfeedbacklevel = PROFORMA_FEEDBACK_LEVEL_INFO;
                    $formdata->teacherfeedbacklevel = PROFORMA_FEEDBACK_LEVEL_DEBUG;

                    if (!empty($grader['result_spec'])) {
                        if ($grader['result_spec']['format'] != "") $formdata->resultspecformat = $grader['result_spec']['format'];
                        if ($grader['result_spec']['structure'] != "") $formdata->resultspecstructure = $grader['result_spec']['structure'];
                        if ($grader['result_spec']['teacher_feedback_level'] != "") $formdata->teacherfeedbacklevel = $grader['result_spec']['teacher_feedback_level'];
                        if ($grader['result_spec']['student_feedback_level'] != "") $formdata->studentfeedbacklevel = $grader['result_spec']['student_feedback_level'];
                    }
                    break;
                }
            }
            if (!$grader_found) {
                throw new moodle_exception("Grader with name: '" . $CFG->{$gradername_setting} ."' and version: '" . $CFG->{$graderversion_setting} . "' for '$expectedgrader' not found on grading middleware.");
            }
        } else {
            throw new moodle_exception("Specification of grader for '$expectedgrader' is missing or incomplete in config.php. Please add or correct the following settings: \n" .
                                       '$CFG->behat_qtype_moopt_grader_name_' . $expectedgrader . "= '<name of the grader configured in the grading middleware>';\n" .
                                       '$CFG->behat_qtype_moopt_grader_version_' . $expectedgrader . "= '<version of the grader configured in the grading middleware>';");
        }

        return $formdata;
    }
}